In [1]:
import pandas as pd

pd.options.display.max_columns = None

#### Read Data

In [2]:
input_data = pd.read_csv("SumitroDatta/PlayerPerGame.csv")
input_data = input_data.sort_values('player_id')

input_data.head()

,seas_id,season,player_id,player,birth_year,pos,age,experience,lg,tm,g,gs,mp_per_game,fg_per_game,fga_per_game,fg_percent,x3p_per_game,x3pa_per_game,x3p_percent,x2p_per_game,x2pa_per_game,x2p_percent,e_fg_percent,ft_per_game,fta_per_game,ft_percent,orb_per_game,drb_per_game,trb_per_game,ast_per_game,stl_per_game,blk_per_game,tov_per_game,pf_per_game,pts_per_game
31346,1,1947,1,Al Brightman,NaN,F,23.0,1,BAA,BOS,58,NaN,NaN,3.8,15.0,0.256,NaN,NaN,NaN,3.8,15.0,0.256,0.256,2.1,3.3,0.627,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,9.8
31347,2,1947,2,Al Lujack,NaN,F,26.0,1,BAA,WSC,5,NaN,NaN,0.2,1.6,0.125,NaN,NaN,NaN,0.2,1.6,0.125,0.125,0.4,1.0,0.400,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.2,0.8
31348,3,1947,3,Al Negratti,NaN,F-C,25.0,1,BAA,WSC,11,NaN,NaN,1.2,6.3,0.188,NaN,NaN,NaN,1.2,6.3,0.188,0.188,0.5,0.7,0.625,NaN,NaN,NaN,0.5,NaN,NaN,NaN,1.8,2.8
31349,4,1947,4,Angelo Musi,NaN,G,28.0,1,BAA,PHW,60,NaN,NaN,3.8,13.6,0.281,NaN,NaN,NaN,3.8,13.6,0.281,0.281,1.7,2.1,0.829,NaN,NaN,NaN,0.4,NaN,NaN,NaN,2.0,9.4
30974,344,1949,4,Angelo Musi,NaN,G,30.0,3,BAA,PHW,58,NaN,NaN,3.3,10.7,0.314,NaN,NaN,NaN,3.3,10.7,0.314,0.314,1.6,2.1,0.756,NaN,NaN,NaN,1.4,NaN,NaN,NaN,1.9,8.2

#### Clean Data

In [3]:
renames = {'seas_id' : 'SeasonID', 
           'season' : 'Season', 
           'player_id' : 'PlayerID', 
           'player' : 'Name', 
           'birth_year' : 'BirthYear', 
           'pos' : 'Position', 
           'age' : 'Age', 
           'experience' : 'YearsExperience', 
           'lg' : 'League', 
           'tm' : 'Team', 
           'g' : 'Games', 
           'gs' : 'GamesStarted', 
           'mp_per_game' : 'MinutesPlayedPerGame', 
           'fg_per_game' : 'FieldGoalsPerGame', 
           'fga_per_game' : 'FieldGoalAttemptsPerGame', 
           'fg_percent' : 'FieldGoalPercent', 
           'x3p_per_game' : 'x3PointsPerGame', 
           'x3pa_per_game' : 'x3PointAttemptsPerGame', 
           'x3p_percent' : 'x3PointPercent', 
           'x2p_per_game' : 'x2PointsPerGame', 
           'x2pa_per_game' : 'x2PointAttemptsPerGame', 
           'x2p_percent' : 'x2PointPercent', 
           'e_fg_percent' : 'EffectiveFieldGoalPercent', 
           'ft_per_game' : 'FreeThrowsPerGame', 
           'fta_per_game' : 'FreeThrowAttemptsPerGame', 
           'ft_percent' : 'FreeThrowPercent', 
           'orb_per_game' : 'OffensiveReboundsPerGame', 
           'drb_per_game' : 'DefensiveReboundsPerGame', 
           'trb_per_game' : 'ReboundsPerGame', 
           'ast_per_game' : 'AssistsPerGame', 
           'stl_per_game' : 'StealsPerGame', 
           'blk_per_game' : 'BlocksPerGame', 
           'tov_per_game' : 'TakeoversPerGame', 
           'pf_per_game' : 'PersonalFoulsPerGame', 
           'pts_per_game' : 'PointsPerGame'
        }

rdata = input_data.rename(columns=renames)
#rdata['BirthYear'] = pd.to_numeric(rdata['BirthYear'], downcast='integer', errors='coerce')
#rdata['Age'] = pd.to_numeric(rdata['Age'], downcast='integer', errors='coerce')
rdata = rdata.astype({'BirthYear' : 'Int64', 'Age' : 'Int64'}, errors='ignore')
rdata.head()

,SeasonID,Season,PlayerID,Name,BirthYear,Position,Age,YearsExperience,League,Team,Games,GamesStarted,MinutesPlayedPerGame,FieldGoalsPerGame,FieldGoalAttemptsPerGame,FieldGoalPercent,x3PointsPerGame,x3PointAttemptsPerGame,x3PointPercent,x2PointsPerGame,x2PointAttemptsPerGame,x2PointPercent,EffectiveFieldGoalPercent,FreeThrowsPerGame,FreeThrowAttemptsPerGame,FreeThrowPercent,OffensiveReboundsPerGame,DefensiveReboundsPerGame,ReboundsPerGame,AssistsPerGame,StealsPerGame,BlocksPerGame,TakeoversPerGame,PersonalFoulsPerGame,PointsPerGame
31346,1,1947,1,Al Brightman,<NA>,F,23,1,BAA,BOS,58,NaN,NaN,3.8,15.0,0.256,NaN,NaN,NaN,3.8,15.0,0.256,0.256,2.1,3.3,0.627,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0,9.8
31347,2,1947,2,Al Lujack,<NA>,F,26,1,BAA,WSC,5,NaN,NaN,0.2,1.6,0.125,NaN,NaN,NaN,0.2,1.6,0.125,0.125,0.4,1.0,0.400,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.2,0.8
31348,3,1947,3,Al Negratti,<NA>,F-C,25,1,BAA,WSC,11,NaN,NaN,1.2,6.3,0.188,NaN,NaN,NaN,1.2,6.3,0.188,0.188,0.5,0.7,0.625,NaN,NaN,NaN,0.5,NaN,NaN,NaN,1.8,2.8
31349,4,1947,4,Angelo Musi,<NA>,G,28,1,BAA,PHW,60,NaN,NaN,3.8,13.6,0.281,NaN,NaN,NaN,3.8,13.6,0.281,0.281,1.7,2.1,0.829,NaN,NaN,NaN,0.4,NaN,NaN,NaN,2.0,9.4
30974,344,1949,4,Angelo Musi,<NA>,G,30,3,BAA,PHW,58,NaN,NaN,3.3,10.7,0.314,NaN,NaN,NaN,3.3,10.7,0.314,0.314,1.6,2.1,0.756,NaN,NaN,NaN,1.4,NaN,NaN,NaN,1.9,8.2

In [4]:
player_info = rdata[['PlayerID', 'Name', 'BirthYear']]
display(player_info[:5])

       PlayerID          Name  BirthYear
31346         1  Al Brightman       <NA>
31347         2     Al Lujack       <NA>
31348         3   Al Negratti       <NA>
31349         4   Angelo Musi       <NA>
30974         4   Angelo Musi       <NA>

In [5]:
column_info = pd.DataFrame({
    'ColumnNames' : list(rdata.columns),
    'DataType' : list(rdata.dtypes)
})
column_info.transpose().head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34
ColumnNames,SeasonID,Season,PlayerID,Name,BirthYear,Position,Age,YearsExperience,League,Team,Games,GamesStarted,MinutesPlayedPerGame,FieldGoalsPerGame,FieldGoalAttemptsPerGame,FieldGoalPercent,x3PointsPerGame,x3PointAttemptsPerGame,x3PointPercent,x2PointsPerGame,x2PointAttemptsPerGame,x2PointPercent,EffectiveFieldGoalPercent,FreeThrowsPerGame,FreeThrowAttemptsPerGame,FreeThrowPercent,OffensiveReboundsPerGame,DefensiveReboundsPerGame,ReboundsPerGame,AssistsPerGame,StealsPerGame,BlocksPerGame,TakeoversPerGame,PersonalFoulsPerGame,PointsPerGame
DataType,int64,int64,int64,object,Int64,object,Int64,int64,object,object,int64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64

In [6]:
season_stats = rdata[['Season', 'PlayerID', 'Age', 'YearsExperience', 'League', 'Team', 'Position', 'Games', 'PointsPerGame', 'AssistsPerGame', 'BlocksPerGame', 'ReboundsPerGame', 'EffectiveFieldGoalPercent']]
display(season_stats[:5])

,Season,PlayerID,Age,YearsExperience,League,Team,Position,Games,PointsPerGame,AssistsPerGame,BlocksPerGame,ReboundsPerGame,EffectiveFieldGoalPercent
31346,1947,1,23,1,BAA,BOS,F,58,9.8,1.0,NaN,NaN,0.256
31347,1947,2,26,1,BAA,WSC,F,5,0.8,0.0,NaN,NaN,0.125
31348,1947,3,25,1,BAA,WSC,F-C,11,2.8,0.5,NaN,NaN,0.188
31349,1947,4,28,1,BAA,PHW,G,60,9.4,0.4,NaN,NaN,0.281
30974,1949,4,30,3,BAA,PHW,G,58,8.2,1.4,NaN,NaN,0.314

In [7]:
player_info.to_csv('ReadyData/PlayerInfo.csv', index=False)

In [8]:
season_stats.to_csv('ReadyData/PlayerSeasonStats.csv', index=False)